spring:
  datasource:
    url: jdbc:h2:mem:currencies
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
  h2:
    console.enabled: true
server:
  error:
    include-message: always
springdoc:
  api-docs:
    path=/api-docs:

exchangeRateApiBaseUrl: https://api.fiscaldata.treasury.gov/services/api/fiscal_service
